package com.inventorysystem_project.entities;

// Importa los enums
import com.inventorysystem_project.entities.enums.EstadoCambio;
import com.inventorysystem_project.entities.enums.TipoCambio; 

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "solicitud_cambio")
@NoArgsConstructor
@AllArgsConstructor
public class SolicitudCambio {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 200)
    private String titulo;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String descripcion;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String justificacion;

    @ManyToOne(fetch = FetchType.LAZY) // Asume que Usuario ya existe en .entities
    @JoinColumn(name = "solicitante_id", nullable = false)
    private Usuario solicitante;

    @Column(columnDefinition = "TEXT")
    private String impacto;

    @Column(columnDefinition = "TEXT")
    private String riesgos;

    @Column(columnDefinition = "TEXT")
    private String planImplementacion;

    @Column(columnDefinition = "TEXT")
    private String planRetirada; // Rollback

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EstadoCambio estado;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TipoCambio tipoCambio;


    // Getters and Setters generated by Lombok (@Data)
    // If you want explicit getters and setters, you can remove @Data and use the following:

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getJustificacion() {
        return justificacion;
    }

    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }

    public Usuario getSolicitante() {
        return solicitante;
    }

    public void setSolicitante(Usuario solicitante) {
        this.solicitante = solicitante;
    }

    public String getImpacto() {
        return impacto;
    }

    public void setImpacto(String impacto) {
        this.impacto = impacto;
    }

    public String getRiesgos() {
        return riesgos;
    }

    public void setRiesgos(String riesgos) {
        this.riesgos = riesgos;
    }

    public String getPlanImplementacion() {
        return planImplementacion;
    }

    public void setPlanImplementacion(String planImplementacion) {
        this.planImplementacion = planImplementacion;
    }

    public String getPlanRetirada() {
        return planRetirada;
    }

    public void setPlanRetirada(String planRetirada) {
        this.planRetirada = planRetirada;
    }

    public EstadoCambio getEstado() {
        return estado;
    }

    public void setEstado(EstadoCambio estado) {
        this.estado = estado;
    }

    public TipoCambio getTipoCambio() {
        return tipoCambio;
    }

    public void setTipoCambio(TipoCambio tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
}